# Generated by Django 4.2.11 on 2024-04-26 20:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                ("type", models.CharField(max_length=255)),
                ("recipient", models.CharField(max_length=255)),
                ("length", models.IntegerField()),
                ("expiry_time", models.IntegerField()),
                ("code", models.CharField(max_length=255)),
                ("is_used", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "ONE TIME PASSWORD",
                "verbose_name_plural": "ONE TIME PASSWORDS",
                "ordering": ["-created_at"],
            },
        ),
    ]
