export const allergies = [
    { "name": "Peanuts", "value": "Peanuts" },
    { "name": "Tree nuts (such as almonds, walnuts, cashews, pistachios)", "value": "Tree nuts" },
    { "name": "Shellfish (such as shrimp, crab, lobster)", "value": "Shellfish" },
    { "name": "Fish", "value": "Fish" },
    { "name": "Milk", "value": "Milk" },
    { "name": "Eggs", "value": "Eggs" },
    { "name": "Soy", "value": "Soy" },
    { "name": "Wheat", "value": "Wheat" },
    { "name": "Gluten", "value": "Gluten" },
    { "name": "Sesame seeds", "value": "Sesame seeds" },
    { "name": "Mustard", "value": "Mustard" },
    { "name": "Celery", "value": "Celery" },
    { "name": "Sulfites", "value": "Sulfites" },
    { "name": "Lupin", "value": "Lupin" },
    { "name": "Mollusks (such as clams, mussels, oysters)", "value": "Mollusks" },
    { "name": "Corn", "value": "Corn" },
    { "name": "Nightshades (such as tomatoes, potatoes, eggplant)", "value": "Nightshades" },
    { "name": "Red meat", "value": "Red meat" },
    { "name": "Pork", "value": "Pork" },
    { "name": "Beef", "value": "Beef" },
    { "name": "Chicken", "value": "Chicken" },
    { "name": "Turkey", "value": "Turkey" },
    { "name": "Coconut", "value": "Coconut" },
    { "name": "Bananas", "value": "Bananas" },
    { "name": "Avocado", "value": "Avocado" },
    { "name": "Strawberries", "value": "Strawberries" },
    { "name": "Citrus fruits (such as oranges, lemons, limes)", "value": "Citrus fruits" },
    { "name": "Melons (such as watermelon, cantaloupe, honeydew)", "value": "Melons" },
    { "name": "Kiwi", "value": "Kiwi" },
    { "name": "Pineapple", "value": "Pineapple" },
    { "name": "Mango", "value": "Mango" },
    { "name": "Papaya", "value": "Papaya" },
    { "name": "Grapes", "value": "Grapes" },
    { "name": "Raspberries", "value": "Raspberries" },
    { "name": "Blueberries", "value": "Blueberries" },
    { "name": "Cranberries", "value": "Cranberries" },
    { "name": "Cherries", "value": "Cherries" },
    { "name": "Pomegranate", "value": "Pomegranate" },
    { "name": "Apricots", "value": "Apricots" },
    { "name": "Peaches", "value": "Peaches" },
    { "name": "Plums", "value": "Plums" },
    { "name": "Nectarines", "value": "Nectarines" },
    { "name": "Apples", "value": "Apples" },
    { "name": "Pears", "value": "Pears" },
    { "name": "Cherimoya", "value": "Cherimoya" },
    { "name": "Lychee", "value": "Lychee" },
    { "name": "Passion fruit", "value": "Passion fruit" },
    { "name": "Jackfruit", "value": "Jackfruit" },
    { "name": "Durian", "value": "Durian" },
    { "name": "Guava", "value": "Guava" },
    { "name": "Dragon fruit", "value": "Dragon fruit" },
    { "name": "Tangerines", "value": "Tangerines" },
    { "name": "Lemons", "value": "Lemons" },
    { "name": "Limes", "value": "Limes" },
    { "name": "Oranges", "value": "Oranges" },
    { "name": "Blood oranges", "value": "Blood oranges" },
    { "name": "Grapefruits", "value": "Grapefruits" },
    { "name": "Kumquats", "value": "Kumquats" },
    { "name": "Clementines", "value": "Clementines" },
    { "name": "Mandarins", "value": "Mandarins" },
    { "name": "Satsumas", "value": "Satsumas" }
]
