import { Red_Hat_Display, DM_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Providers from "@/lib/contexts";

const sans = DM_Sans({ subsets: ["latin"] });
export const displayFont = Red_Hat_Display({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sans.className}>
        <Providers>
          <Toaster />

          {children}
        </Providers>
      </body>
    </html>
  );
}
